# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gabriel Magno de Oliveira Silva
email: magno@dcc.ufmg.br
description: > # this means to ignore newlines until "baseurl:"
  Computer Science PhD student.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gmagno.net" # the base hostname & protocol for your site
twitter_username: gabrielmagno
github_username:  gabrielmagno

# Build settings
markdown: kramdown
theme: minima

permalink: /blog/:title/

#gems: [jekyll/scholar]
plugins: ['jekyll/scholar']

scholar:
  style: _bibliography/my_template.csl
  #style: associacao-brasileira-de-normas-tecnicas
  locale: en

  sort_by: year,month
  order: descending,descending
  bibliography_list_tag: ul

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibliography-item

  repository: papers 

  replace_strings: true
  join_strings:    true

  #use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

